### ISSUE TITLE
Why not lodash??

### ISSUE THREAD

**Issue by ika18** [mjpclab/object-hierarchy-access#1]
https://lodash.com/docs/4.17.11#get
https://lodash.com/docs/4.17.11#set
黑人问号脸

**Comment by mjpclab** [comment]
Thanks @ika18 , I didn't know this API before. I think this package is much simpler without a lot of guard check(for example to avoid `hasOwnProperty` to be overwritten in instance, they use this: https://github.com/lodash/lodash/blob/master/.internal/assignValue.js).
